### ISSUE TITLE
"has advancement" syntax no longer included in the new update

### ISSUE THREAD

**Issue by JosTheDude** [hotpocket184/skript-advancements#10]
I updated my Skript-Advancements but the "has advancement" syntax has disappeared :(

**Comment by hotpocket184** [comment]
To check it you can now use the player advancements expression.
`if advancements of player contains the advancement "adventure/root"`
`if custom advancements of player contains the custom advancement "tab/advancement"`
The same goes for granting and revoking advancements. I'll add the syntax in the next update just to clear some things up.
