### ISSUE TITLE
BUG: or not? | on advancement event

### ISSUE THREAD

**Issue by mestow** [hotpocket184/skript-advancements#12]
when i use the "on advancement" event, and i reload the scripts. skript return this message

![imagen](https://user-images.githubusercontent.com/98564343/201032060-39883f5f-87a7-4332-b68a-cacd406c87b2.png)

and i no have idea why this happens

**Comment by hotpocket184** [comment]
Could you please send the results of /skinfo?

**Comment by hotpocket184** [comment]
My guess is that it would be because it is a Purpur server.
