### ISSUE TITLE
Advancements Dispay : hidden/range

### ISSUE THREAD

**Issue by AKtomik** [hotpocket184/skript-advancements#22]
Hi ! I have somes suggestions about Advancements Dispay :
### the first : hidden
In minecraft, somes advancements are hidden, and dispay only if we done it.
![image](https://user-images.githubusercontent.com/97125853/213802392-fdc95723-dbba-4a68-b874-2867e4afb9bb.png)
![image](https://user-images.githubusercontent.com/97125853/213802278-0e3c9770-cc48-4443-9b3d-902622bbccd9.png)
In the JSON code, its the `"hidden": true` experssion which make that.

**It would be nice to be able to use the hidden expression !**

I propose an expression like :
 `[the] display hidden of [the] [last (created|made)] [custom] advancement`
 with default value set to false
Example Usage
```
create advancement named "secret":
   set display hidden of advancement to true
   build advancement
```
### the second : range
Using skript-advancements, all incomplete advancements are display.
![image](https://user-images.githubusercontent.com/97125853/213798109-008b5d27-157f-49b9-a5ff-36d127c7670c.png)

But in minecraft it's not like this :
-> incomplete advancements are only displayed if a completed advancement is within a range of 2.
![image](https://user-images.githubusercontent.com/97125853/213798572-1b204430-b883-4d02-9f94-b5dfcedaf53d.png)
![image](https://user-images.githubusercontent.com/97125853/213798436-94ef37c1-45cb-4146-8134-0f88443838ba.png)

**It would be nice to be able to configure that !**

I propose an expression like :
 `[the] display range of [the] [last (created|made)] [custom] advancement`
 with default value set to 2 (and -1 make show all)
Example Usage
```
create advancement named "far":
   set display range of advancement to 2
   build advancement
```
This experssion make possible to customise the display range,
and can also make the job of `display hidden` when you set it to 0 !

### So
So, it's just some suggestions, you do what you want with them, but it will be really nice to be able do that !!
Thank for your work on this useful addon !

**Comment by hotpocket184** [comment]
Great idea. I will get to work on it right away.
