### ISSUE TITLE
On advancement isn't working

### ISSUE THREAD

**Issue by CatDev222** [hotpocket184/skript-advancements#26]
I'm trying to make it so when a player completes the "dragonmaster" achievement, they get an item, but it doesn't work
Code:
```
on advancement:
   if "%event-advancement%" contains "my_tab/dragonmaster":
      give dirt to player

```
Skript version: 2.6.4
Skript-Advancements version: 1.5.6
Server version: Paper 1.19.4

I don't get any errors, the event just doesn't trigger and I have no idea why

**Comment by hotpocket184** [comment]
That event is for actual advancements, like from datapacks or Minecraft itself. Skript-advancements uses UltimateAdvancementAPI to make advancements with packets. The event you should instead use is `on advancement progress` and then check if the progress is complete.
```vb
on advancement progress:
   if future event-number is max progress of event-customadvancement:
      # other things here```

It can be quite tedious to have this everywhere you want it so I will make an event for it eventually.

**Comment by CatDev222** [comment]
Alright, thank you

**Comment by CatDev222** [comment]
I still have an issue though. I want the event to fire when progress is made on a specific advancement. This is because I want to add specific rewards for specific advancements. Is there a way to to this?
