### ISSUE TITLE
how to make the group not go together with other groups

### ISSUE THREAD

**Issue by SilverOfDragon** [hotpocket184/skript-advancements#27]
![2023-06-09_00 49 29](https://github.com/hotpocket184/skript-advancements/assets/136030302/496aec9b-c4ea-4dfd-bd0d-cd4529292451)

Have now tried for 2 hours to get them not to stick together. The problem is that TNT is connected with the Wooden hoe and with the fishing rod. Trying to make them stick to white wool only. also those from the TNT group can only hang together, and the same with the Stone group. How do I do it???

**Comment by hotpocket184** [comment]
I'm afraid you can't. Advancements will always be connected to their parent advancement so if another advancement is in the way of the line then they will appear connected. To my knowledge, you cannot change the lines themselves or where they go.
