### ISSUE TITLE
Troubled Icon

### ISSUE THREAD

**Issue by HaciGandalf** [hotpocket184/skript-advancements#5]
`display toast to player titled "Quest Complete" using icon diamond using frame task`

When I place a player's head in the icon part in the example, the skin is not visible. it just looks like steven's head.

![image](https://user-images.githubusercontent.com/65103582/179088721-6f723ccc-3be6-46f5-8596-37482f8bac9c.png)

the code i run: `send toast to player titled "&d&l%uncolored line {_x} of lore of {esyalar::topaz}% GANİMET!" with icon {esyalar::topaz} using frame goal`

{esyalar::topaz} = skined player head 
![image](https://user-images.githubusercontent.com/65103582/179088968-e81c8bb8-69f9-4874-9dea-d5141819f5b7.png)

**Comment by hotpocket184** [comment]
I'll add NBT API to the project in order to accomplish this. It should be fixed next update.
